version: '3'

services:
  composer:
    image: composer:2.0.14
    volumes:
    - "../:/app"

  app:
    build:
      context: ..
      dockerfile: ./.docker/app.Dockerfile
    depends_on:
      - composer
    volumes:
    - "../:/app"
    - "./conf.ini:/usr/local/etc/php/conf.d/conf.ini"

networks:
  default:
